# Generated by Django 2.0 on 2018-03-06 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billboard',
            fields=[
                ('billboard_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=10, unique=True)),
                ('content', models.TextField(max_length=255)),
                ('staff_id', models.IntegerField()),
                ('publish_time', models.DateTimeField(default=datetime.datetime(2018, 3, 6, 19, 46, 8, 852265))),
            ],
            options={
                'db_table': 'billboard',
                'ordering': ['-publish_time'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.IntegerField(primary_key=True, serialize=False)),
                ('car_model', models.CharField(max_length=10)),
                ('car_number', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'car',
                'ordering': ['car_id', 'car_number'],
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('house_id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100, unique=True)),
                ('text_description', models.CharField(max_length=100)),
                ('image_description', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'house',
                'ordering': ['house_id', 'location'],
            },
        ),
        migrations.CreateModel(
            name='HouseHolder',
            fields=[
                ('householder_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('realname', models.CharField(max_length=10)),
                ('tel', models.CharField(max_length=11, unique=True)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('register_time', models.DateTimeField(default=datetime.datetime(2018, 3, 6, 19, 46, 8, 847265))),
            ],
            options={
                'db_table': 'householder',
                'ordering': ['householder_id', 'username'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.IntegerField(primary_key=True, serialize=False)),
                ('realname', models.CharField(max_length=10)),
                ('id_number', models.CharField(max_length=18, unique=True)),
                ('age', models.SmallIntegerField()),
                ('job', models.CharField(max_length=10)),
                ('checkin_time', models.DateTimeField(default=datetime.datetime(2018, 3, 6, 19, 46, 8, 851265))),
                ('salary', models.FloatField()),
            ],
            options={
                'db_table': 'staff_profile',
            },
        ),
        migrations.CreateModel(
            name='RelCarHolder',
            fields=[
                ('rel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('car_id', models.IntegerField(unique=True)),
                ('householder_id', models.IntegerField()),
                ('checkin_time', models.DateTimeField(default=datetime.datetime(2018, 3, 6, 19, 46, 8, 856265))),
            ],
            options={
                'db_table': 'rel_car_holder',
                'ordering': ['checkin_time'],
            },
        ),
        migrations.CreateModel(
            name='RelHouseHolder',
            fields=[
                ('rel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('house_id', models.IntegerField(unique=True)),
                ('householder_id', models.IntegerField()),
                ('checkin_time', models.DateTimeField(default=datetime.datetime(2018, 3, 6, 19, 46, 8, 855265))),
                ('moveout_time', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999))),
            ],
            options={
                'db_table': 'rel_house_holder',
                'ordering': ['-checkin_time'],
            },
        ),
        migrations.CreateModel(
            name='RelHouseholderRepair',
            fields=[
                ('rel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('householder_id', models.IntegerField()),
                ('repair_id', models.IntegerField()),
            ],
            options={
                'db_table': 'rel_householder_repair',
                'ordering': ['repair_id'],
            },
        ),
        migrations.CreateModel(
            name='RelStaffProfile',
            fields=[
                ('rel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('staff_id', models.IntegerField()),
                ('profile_id', models.IntegerField()),
            ],
            options={
                'db_table': 'rel_staff_profile',
            },
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('repair_id', models.IntegerField(primary_key=True, serialize=False)),
                ('house_id', models.IntegerField()),
                ('repair_description', models.CharField(max_length=100)),
                ('publish_time', models.DateTimeField(default=datetime.datetime(2018, 3, 6, 19, 46, 8, 849265))),
                ('staff_id', models.IntegerField()),
                ('repair_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'repair',
                'ordering': ['-publish_time'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('tel', models.CharField(max_length=11, unique=True)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('level', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
    ]
