# Generated by Django 2.0.3 on 2018-03-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180323_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='householder',
            name='householder_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
