# Generated by Django 2.0.3 on 2018-03-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180323_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='householder',
            name='realname',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='householder',
            name='tel',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
