# Generated by Django 2.0.3 on 2018-04-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_receive',
            field=models.CharField(default='小区物业', max_length=10),
        ),
    ]
