# Generated by Django 2.0.3 on 2018-04-18 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20180418_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_createtime',
            field=models.TimeField(default=datetime.datetime(2018, 4, 18, 16, 22, 1, 369418)),
        ),
    ]
