# Generated by Django 2.0.3 on 2018-04-18 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20180418_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_createtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
