# Generated by Django 2.0.3 on 2018-04-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20180418_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_paytime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
